services:
  stock-db-app:
    build: .
    # depends_on:
    #   - stock-db

  stock-db:
    image: postgres:16.4-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
